name:
  maximum_length: 50
password:
  minimum_length: 6
email:
  maximum_length: 255
gravatar:
  default_size: 80
  index_page_size: 50
remember_me:
  checked: "1"
time_zone: "Asia/Bangkok"
password_reset:
  maximum_time_expired: 2
micropost:
  maximum_length: 140
picture_upload:
  maximum_size: 5
  limit_width: 400
  limit_height: 400
  accept_filetype: "image/jpeg,image/gif,image/png"
